dtfile <- "../household_power_consumption.txt"
dt <- read.table(dtfile, header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
subsetdt <- dt[dt$Date %in% c("1/2/2007","2/2/2007") ,]
datetime <- strptime(paste(subsetdt$Date, subsetdt$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
globalactivepwr <- as.numeric(subsetdt$Global_active_power)
globalreactivepwr <- as.numeric(subsetdt$Global_reactive_power)
voltage <- as.numeric(subsetdt$Voltage)
submtr1 <- as.numeric(subsetdt$Sub_metering_1)
submtr2 <- as.numeric(subsetdt$Sub_metering_2)
submtr3 <- as.numeric(subsetdt$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2)) 
plot(datetime, globalactivepwr, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(datetime, voltage, type="l", xlab="datetime", ylab="Voltage")
plot(datetime, submtr1, type="l", ylab="Energy Submetering", xlab="")
lines(datetime, submtr2, type="l", col="red")
lines(datetime, submtr3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(datetime, globalreactivepwr, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()